import type { Book } from '@/types';

const today = new Date();
const daysAgo = (d: number) => new Date(today.getTime() - d * 86400000).toISOString();

export const sampleBooks: Book[] = [
  {
    id: 'b1',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    type: 'book',
    coverColor: '#3B5998',
    coverAccent: '#8B9DC3',
    coverImage: 'https://covers.openlibrary.org/b/isbn/0374533555-L.jpg',
    dateAdded: daysAgo(120),
    lastRevisited: daysAgo(2),
    notes: 'Fundamental rethinking of how we make decisions. The System 1/System 2 framework has changed how I notice my own thinking patterns.',
    concepts: [
      {
        id: 'c1',
        bookId: 'b1',
        text: 'System 1 and System 2 Thinking',
        context: 'Our minds operate in two modes: fast, intuitive System 1 and slow, deliberate System 2. Most of our daily decisions are made by System 1 without our conscious awareness.',
        personalNote: 'I notice System 1 taking over when I make snap judgments about people at work.',
        skill: 'Decision-making',
        dateAdded: daysAgo(120),
        lastRevisited: daysAgo(2),
        timesRevisited: 8,
        retentionDays: 118,
      },
      {
        id: 'c2',
        bookId: 'b1',
        text: 'Anchoring Effect',
        context: 'Our estimates and decisions are heavily influenced by the first number or idea we encounter, even when that anchor is completely arbitrary.',
        personalNote: 'Explains why salary negotiations are so affected by whoever names a number first.',
        skill: 'Negotiation',
        dateAdded: daysAgo(115),
        lastRevisited: daysAgo(18),
        timesRevisited: 4,
        retentionDays: 97,
      },
      {
        id: 'c3',
        bookId: 'b1',
        text: 'Loss Aversion',
        context: 'The pain of losing something is psychologically about twice as powerful as the pleasure of gaining the same thing. This asymmetry drives much of human behavior.',
        personalNote: 'This is why I hold onto clothes I never wear — the pain of giving them away feels worse than the pleasure of a clean closet.',
        dateAdded: daysAgo(110),
        lastRevisited: daysAgo(45),
        timesRevisited: 2,
        retentionDays: 65,
      },
    ],
  },
  {
    id: 'b2',
    title: 'The Death and Life of Great American Cities',
    author: 'Jane Jacobs',
    type: 'book',
    coverColor: '#6B4E3D',
    coverAccent: '#C4956A',
    coverImage: 'https://covers.openlibrary.org/b/isbn/067974195X-L.jpg',
    dateAdded: daysAgo(90),
    lastRevisited: daysAgo(10),
    notes: 'A revelation about how cities actually work versus how planners think they work. Eyes on the street changed how I walk through my neighborhood.',
    concepts: [
      {
        id: 'c4',
        bookId: 'b2',
        text: 'Eyes on the Street',
        context: 'Sidewalk safety is maintained not by police but by an intricate network of voluntary controls among people themselves — shop owners, residents, passersby who naturally watch the street.',
        personalNote: 'My block feels safest where the bodega owner sits outside. Jacobs would smile.',
        skill: 'Urban design',
        dateAdded: daysAgo(85),
        lastRevisited: daysAgo(10),
        timesRevisited: 5,
        retentionDays: 75,
      },
      {
        id: 'c5',
        bookId: 'b2',
        text: 'Mixed Primary Uses',
        context: 'Districts need a mix of primary uses — residences, offices, shops, entertainment — that bring people onto the streets at different times of day, creating continuous vitality.',
        personalNote: 'The dead zone near my office is all offices. No wonder it feels eerie after 6pm.',
        dateAdded: daysAgo(80),
        lastRevisited: daysAgo(35),
        timesRevisited: 3,
        retentionDays: 45,
      },
    ],
  },
  {
    id: 'b3',
    title: 'When Breath Becomes Air',
    author: 'Paul Kalanithi',
    type: 'book',
    coverColor: '#87CEEB',
    coverAccent: '#4682B4',
    coverImage: 'https://covers.openlibrary.org/b/isbn/081298840X-L.jpg',
    dateAdded: daysAgo(60),
    lastRevisited: daysAgo(25),
    notes: 'Devastatingly beautiful. A neurosurgeon facing his own mortality asks what makes life meaningful.',
    concepts: [
      {
        id: 'c6',
        bookId: 'b3',
        text: 'The Doctor-Patient Relationship as Sacred Trust',
        context: "A physician's duty extends beyond technical treatment. In moments of crisis, the doctor holds not just a patient's body but their identity — who they are and who they hoped to become.",
        personalNote: 'Made me think about how we treat vulnerability in professional settings.',
        dateAdded: daysAgo(55),
        lastRevisited: daysAgo(25),
        timesRevisited: 2,
        retentionDays: 30,
      },
      {
        id: 'c7',
        bookId: 'b3',
        text: 'Finding Meaning Through Mortality',
        context: "Confronting death doesn't diminish life but clarifies what matters. Kalanithi found that meaning isn't waiting to be discovered — it's built through the commitments we choose to honor.",
        personalNote: 'I keep returning to this. What commitments am I honoring?',
        dateAdded: daysAgo(50),
        lastRevisited: daysAgo(40),
        timesRevisited: 1,
        retentionDays: 10,
      },
    ],
  },
  {
    id: 'b4',
    title: 'The Overstory',
    author: 'Richard Powers',
    type: 'book',
    coverColor: '#2E8B57',
    coverAccent: '#90EE90',
    coverImage: 'https://covers.openlibrary.org/b/isbn/039363552X-L.jpg',
    dateAdded: daysAgo(30),
    lastRevisited: daysAgo(5),
    notes: 'Trees as characters, forests as communities. Changed how I see the maple outside my window.',
    concepts: [
      {
        id: 'c8',
        bookId: 'b4',
        text: 'Trees as Social Organisms',
        context: 'Trees communicate through underground fungal networks, sharing nutrients and warning of threats. A forest is not a collection of individuals but a community with its own intelligence.',
        personalNote: 'The "wood wide web" — I think about this every time I walk through the park.',
        dateAdded: daysAgo(25),
        lastRevisited: daysAgo(5),
        timesRevisited: 3,
        retentionDays: 20,
      },
    ],
  },
  {
    id: 'b5',
    title: 'Entangled Life',
    author: 'Merlin Sheldrake',
    type: 'book',
    coverColor: '#9370DB',
    coverAccent: '#DDA0DD',
    coverImage: 'https://covers.openlibrary.org/b/isbn/0525510311-L.jpg',
    dateAdded: daysAgo(14),
    lastRevisited: null,
    notes: 'Fungi as the hidden architects of life. Mind-expanding.',
    concepts: [
      {
        id: 'c9',
        bookId: 'b5',
        text: 'Mycorrhizal Networks',
        context: 'Over ninety percent of plants depend on fungal partners. These mycorrhizal relationships predate roots — fungi taught plants how to live on land.',
        personalNote: 'Partnership as the fundamental unit of life, not competition.',
        dateAdded: daysAgo(12),
        lastRevisited: null,
        timesRevisited: 0,
        retentionDays: 0,
      },
      {
        id: 'c10',
        bookId: 'b5',
        text: 'Radical Mycology',
        context: 'Fungi challenge our categories: they are neither plant nor animal. They dissolve the boundaries we impose on life, suggesting that individuality itself is a spectrum.',
        personalNote: 'What if identity is more like a fungal network than a fortress?',
        dateAdded: daysAgo(10),
        lastRevisited: null,
        timesRevisited: 0,
        retentionDays: 0,
      },
    ],
  },
];
